### Authentication (Auth APIs)

# User Registration
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
  "username": "Trần Phương Thái",
  "email": "user@example.com",
  "password": "password123",
}

# User Login
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

# User Logout
GET http://localhost:5000/api/v1/auth/signout

# Google Login
POST http://localhost:5000/api/v1/auth/google
Content-Type: application/json

{
  "accessToken": "token",
}

### User Profile

# Update User Profile
POST http://localhost:5000/api/v1/user/update-profile
Authorization: Bearer ACCESS_TOKEN
Content-Type: application/json

{
  "username": "Nguyễn Văn A",
  "phone": "0987654321",
  "location": "Hà Nội",
  "bio": "Software Engineer with 2 years of experience.",
  "photoURL": "https://example.com/avatar.jpg",
  "education": {
    "institution": "Đại học Bách Khoa",
    "degree": "Cử nhân",
    "field_of_study": "Khoa học máy tính",
    "start_date": "2019-09-01",
    "end_date": "2023-06-01",
    "description": "Studied AI and Machine Learning."
  },
  "experience": {
    "company_name": "FPT Software",
    "position": "Software Engineer",
    "start_date": "2023-06-01",
    "end_date": "2024-02-01",
    "description": "Developed web applications using ReactJS."
  },
"skills": ["65f7a1b3d1a2e3f4c5b6a701", "65f7a1b3d1a2e3f4c5b6a703"]
}

### Job Listings

# Get All Jobs
GET http://localhost:5000/api/v1/job

# Get Recommended Jobs for a User
GET http://localhost:5000/api/v1/job/recommend
Authorization: Bearer ACCESS_TOKEN
# Get Job Details
GET http://localhost:5000/api/v1/job/JOB_ID_HERE
example response:
"    "job": {
        "_id": "67cd8f995d37dc74b501f3ab",
        "title": "Lập trình viên Python",
        "company": {
            "name": "Công ty TNHH Công nghệ ABC",
            "logo": "https://example.com/logo.png",
            "background_image": "https://example.com/bg.jpg",
            "location": "Hà Nội"
        },
        "skills": [],
        "location": "Hà Nội",
        "salary_range": "$2000 - $2500",
        "reasons_to_join": "<ul><li>Môi trường làm việc tốt</li><li>Có cơ hội thăng tiến</li><li>Lương thưởng hấp dẫn</li></ul>",
        "required_experience": "<p>Yêu cầu tối thiểu: <strong>2 năm kinh nghiệm Python</strong></p>",
        "responsibility": "<p>Phát triển API backend với Django</p>",
        "description": "<p>Công ty cần tuyển lập trình viên backend Python...</p>",
        "posted_time": "vài giây trước"
    }"
# Recruiter Creates a Job Post
POST http://localhost:5000/api/v1/job
Authorization: Bearer RECRUITER_ACCESS_TOKEN
Content-Type: application/json

{
  "title": "Lập trình viên Python",
  "skills": [
    "65f0a8b3e4b0f1a2d4c9a3d3",
    "65f0a8b3e4b0f1a2d4c9a3d4"
  ],
  "location": "Hà Nội",
  "salary_range": "$2000 - $2500",
  "reasons_to_join": "<ul><li>Môi trường làm việc tốt</li><li>Có cơ hội thăng tiến</li><li>Lương thưởng hấp dẫn</li></ul>",
  "required_experience": "<p>Yêu cầu tối thiểu: <strong>2 năm kinh nghiệm Python</strong></p>",
  "responsibility": "<p>Phát triển API backend với Django</p>",
  "description": "<p>Công ty cần tuyển lập trình viên backend Python...</p>"
}


# Update a Job Post
PUT http://localhost:5000/api/v1/job/JOB_ID_HERE
Authorization: Bearer RECRUITER_ACCESS_TOKEN
Content-Type: application/json

{
  "title": "Backend Developerr",
  "skills": [
    "65e0f6c83c8c3e12a4dfe228",
    "65e0f6f13c8c3e12a4dfe229"
  ]
}

# Delete a Job Post
DELETE http://localhost:5000/api/v1/job/JOB_ID_HERE
Authorization: Bearer RECRUITER_ACCESS_TOKEN

### Upload Image
### Only one file (png,jpg) ./path_to_your_image.jpg
POST http://localhost:5000/api/v1/upload/image
Content-Type: multipart/form-data

### Upload Resume
### Only one file (pdf) path_to_your_resume.pdf
POST http://localhost:5000/api/v1/upload/resume
Content-Type: multipart/form-data

### Apply for a job
POST http://localhost:5000/api/v1/application
Authorization: Bearer USER_ACCESS_TOKEN
Content-Type: application/json

{
  "job_id": "65e0f5b93c8c3e12a4dfe217",
  "resume": "https://res.cloudinary.com/example/uploads/resumes/abc123.pdf",
  "cover_letter": "I am interested in this position."
}

###  Get Applied Jobs for Candidate
GET http://localhost:5000/api/v1/application
Authorization: Bearer USER_ACCESS_TOKEN

### Get Applicants for a Job (Recruiter Only)
GET http://localhost:5000/api/v1/application/job/job_id
Authorization: Bearer RECRUITER_ACCESS_TOKEN

### Favorite job
### Add favorite job
POST http://localhost:5000/api/v1/favorite
Authorization: Bearer USER_ACCESS_TOKEN

{
  "jobId": "67c1e258ba3d3e783ee64a91"
}

### Get favorite job
GET http://localhost:5000/api/v1/favorite
Authorization: Bearer USER_ACCESS_TOKEN
### Remove favorite job
DELETE  http://localhost:5000/api/v1/favorite/ID
Authorization: Bearer USER_ACCESS_TOKEN


### Get list job and skill for first login or update profile
GET http://localhost:5000/api/v1/job/listings 
Content-Type: application/json

response: "id,name"

GET http://localhost:5000/api/v1/job/skills/:id (id from api job/listings)
Content-Type: application/json
