name: Start App with GitHub Secrets

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      APP_PORT: ${{ secrets.APP_PORT }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      CLIENT: ${{ secrets.CLIENT }}
      RECRUITER: ${{ secrets.RECRUITER }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
      PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}

    steps:
      - name: Clone repository manually
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.ref_name }}

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Create .env file from GitHub Secrets
        run: |
          echo "APP_PORT=$APP_PORT" >> .env
          echo "CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY" >> .env
          echo "CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET" >> .env
          echo "CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env
          echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET" >> .env
          echo "REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET" >> .env
          echo "CLIENT=$CLIENT" >> .env
          echo "RECRUITER=$RECRUITER" >> .env
          echo "MONGO_URI=$MONGO_URI" >> .env
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
          echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
          echo "PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID" >> .env
          echo "PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET" >> .env
        working-directory: ./server

      - name: Start app
        run: npm start
        working-directory: ./server
